import {getPreviewConfig} from './preview-config.js';
import {isNative,sendNative,cancelNative,startNativeRecording,stopNativeRecording,nativeRecording} from './native.js';
import {books,lessons,questions,sentence} from './data.js';
const $=s=>document.querySelector(s);
const preview=getPreviewConfig(location.search,isNative());
const paths={home:'M3 10 12 3l9 7v10H3Z M9 20v-7h6v7',book:'M12 5C8 2 3 4 3 4v15s5-2 9 1c4-3 9-1 9-1V4s-5-2-9 1Zm0 0v15',review:'M4 8a8 8 0 1 1-1 7 M4 3v5h5 M12 8v5l3 2',grammar:'M5 3h14v18H5Z M8 7h8 M8 11h8 M8 15h5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',sound:'M11 4 6 8H3v8h3l5 4Z M15 8a6 6 0 0 1 0 8 M18 5a10 10 0 0 1 0 14',arrow:'M4 12h16 M14 6l6 6-6 6',check:'M5 12l4 4L19 6',leaf:'M20 3C7 1 1 12 7 18s17-2 13-15Z M5 21 16 8'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.book}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=()=>new Date().toLocaleDateString('en-CA');
let state;try{state=(!preview.enabled&&window.hiyoriSavedState)||JSON.parse(localStorage.getItem(preview.storageKey))}catch{}state={done:{},mistakes:[],days:{},goal:15,rate:.85,book:0,...state};
let view=preview.view,book=state.book,session=null,recorder=null,stream=null,audioURL=null,recordTimer=null,recordPending=false;
function save(){if(isNative())sendNative('save',{value:state});try{localStorage.setItem(preview.storageKey,JSON.stringify(state))}catch{toast('浏览器无法保存进度，请检查存储设置。')}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500)}
const shuffled=a=>a.map(x=>({x,r:Math.random()})).sort((a,b)=>a.r-b.r).map(o=>o.x);
function speak(text,slow=false){if(isNative()){sendNative('speak',{text,rate:slow?.6:Number(state.rate)});return}if(!('speechSynthesis'in window)){toast('此浏览器不支持朗读，请使用支持语音合成的浏览器。');return}const voices=speechSynthesis.getVoices().filter(v=>v.lang.startsWith('ja'));if(!voices.length){toast('未找到日语语音，请在系统语音设置中添加日语。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.voice=voices[0];u.rate=slow?.6:Number(state.rate);u.onerror=e=>{if(e.error!=='interrupted'&&e.error!=='canceled')toast('朗读未能播放，请检查系统日语语音。')};speechSynthesis.speak(u)}
if('speechSynthesis'in window)speechSynthesis.getVoices();
function render(){
 const labels={home:'课程',kana:'五十音',review:'错题复习',grammar:'语法',settings:'设置'};
 const total=Object.keys(state.done).length;
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">新标准日本语</div><nav class="nav" aria-label="主导航">${[['home','book'],['kana','home'],['review','review'],['grammar','grammar'],['settings','settings']].map(([v,i])=>`<button data-nav="${v}" class="${view===v?'active':''}">${icon(i)}${labels[v]}</button>`).join('')}</nav></aside><main class="main"><header class="topbar"><div class="breadcrumb"><span class="mobilebrand">新标准日本语 / </span>${labels[view]}${preview.enabled?' · 试用':''}</div><span class="progresslabel">已学习 ${total} / 80 课</span></header><div id="page">${view==='home'?home():view==='kana'?kana():view==='review'?review():view==='grammar'?grammar():settings()}</div><footer class="footer"><span>原创配套练习 · 非教材官方产品</span>${preview.enabled?'<span>试用记录单独保存</span>':''}</footer></main></div>`;
 bind();
}
function home(){
 const ls=lessons.filter(l=>l.book===book),next=ls.find(l=>!state.done[l.id]);
 const today=Math.floor((state.days[day()]||0)/60);
 return `<div class="heading"><div><h1>课程</h1><p class="sub">按教材顺序学习，也可直接选择课次。</p></div><button class="pill" data-nav="settings">今日 ${today} / ${state.goal} 分钟</button></div><div class="tabs" role="tablist">${books.map((b,i)=>`<button role="tab" aria-selected="${book===i}" data-book="${i}" class="${book===i?'active':''}">${b.name}</button>`).join('')}</div><p class="sub course-note">${book<2?'按课次核心语法编排 · 每课 6 组练习':'按课次话题编排 · 原创延伸句型，未逐条覆盖教材语法'}</p><section class="lessonlist">${ls.map((l,i)=>`${i%4===0?`<div class="unithead"><strong>第 ${Math.floor(i/4)+1} 单元</strong><small>${ls.slice(i,i+4).filter(x=>state.done[x.id]).length} / 4 课已学习</small></div>`:''}<button class="lesson ${l.id===next?.id?'current':''}" data-start="${l.id}"><span class="lessonnum">${String(l.no).padStart(2,'0')}</span><span class="lessontext"><strong>${l.title}</strong><p>${esc(l.grammar)}</p></span><span class="lessonend">${state.done[l.id]?'已学习':l.id===next?.id?'开始学习':'学习'} ${icon('arrow')}</span></button>`).join('')}</section>`;
}
const kanaRows=[['あいうえお','アイウエオ','a i u e o'],['かきくけこ','カキクケコ','ka ki ku ke ko'],['さしすせそ','サシスセソ','sa shi su se so'],['たちつてと','タチツテト','ta chi tsu te to'],['なにぬねの','ナニヌネノ','na ni nu ne no'],['はひふへほ','ハヒフヘホ','ha hi fu he ho'],['まみむめも','マミムメモ','ma mi mu me mo'],['や ゆ よ','ヤ ユ ヨ','ya - yu - yo'],['らりるれろ','ラリルレロ','ra ri ru re ro'],['わ   を','ワ   ヲ','wa - - - o'],['ん','ン','n']];
function kana(){return `<div class="heading"><div><h1>五十音</h1><p class="sub">点击假名听发音。先认识平假名，再熟悉片假名。</p></div></div><div class="card full"><p class="sub" style="margin-bottom:23px">清音入门表 · 大字为平假名，小字为片假名与罗马音。助词 は、へ、を 分别读 wa、e、o。浊音、拗音和长音仍需专项学习。</p><div class="kana">${kanaRows.map(([h,k,r])=>[...h].map((c,i)=>c===' '?'<span></span>':`<button data-say="${c}">${c}<small>${k[i]} · ${r.split(' ')[i]}</small></button>`).join('')).join('')}</div></div>`}
function review(){return `<div class="heading"><div><h1>错题复习</h1><p class="sub">答错的知识点会留在这里。复习答对后，自动移出错题本。</p></div></div>${state.mistakes.length?`<div class="card full"><h3>${state.mistakes.length} 道题，值得再想一遍</h3><button class="primary" id="reviewStart">开始错题复习 ${icon('arrow')}</button></div>${state.mistakes.map(m=>{const l=lessons[m.id];return `<div class="card full"><h3>${books[l.book].name} · 第 ${l.no} 课　${l.title}</h3><p class="jp">${l.grammar}</p><p class="sub">${l.note}</p></div>`}).join('')}`:`<div class="card full empty"><h2>暂无错题</h2><p class="sub">答错的题目会保存在这里。</p><button class="primary" style="margin-top:25px" data-nav="home">去学习</button></div>`}`}
function grammar(){return `<div class="heading"><div><h1>语法</h1><p class="sub">中文解释，日语例句。把零散的知识连起来。</p></div></div><input class="search" id="grammarSearch" aria-label="搜索语法" placeholder="搜索句型、主题或中文解释，例如：条件、と思います"><div class="grid" id="grammarGrid" style="margin-top:23px">${grammarCards(lessons)}</div>`}
function grammarCards(ls){return ls.length?ls.map(l=>`<div class="card grammarcard"><div class="eyebrow">${books[l.book].name} · 第 ${l.no} 课</div><p class="jp">${l.grammar}</p><p>${l.note}</p><button class="textbtn" data-start="${l.id}">练习这个知识点 →</button></div>`).join(''):'<p class="sub">没有找到对应内容，试试其他关键词。</p>'}
function settings(){return `<h1>设置</h1><div class="card full" style="margin-top:25px"><div class="formrow"><label for="goal">每日学习目标</label><select id="goal">${[10,15,20,30].map(n=>`<option value="${n}" ${state.goal===n?'selected':''}>${n} 分钟 / 天</option>`).join('')}</select></div><div class="formrow"><label for="rate">日语朗读语速</label><select id="rate">${[[.65,'慢速'],[.85,'适中'],[1,'正常']].map(([n,t])=>`<option value="${n}" ${Number(state.rate)===n?'selected':''}>${t}</option>`).join('')}</select></div><button class="pill" data-say="こんにちは。今日も一緒に勉強しましょう。">${icon('sound')} 试听日语语音</button><p class="sub" style="margin-top:22px">${isNative()?'课程已内置，可离线学习。进度保存在这台 iPad；录音仅用于本次练习，不上传，退出或进入后台时释放。朗读使用系统日语语音，首次可能需要联网下载语音。':'进度只保存在当前浏览器。录音只在本次练习中回放，不上传。朗读使用设备的日语语音，可能需要先安装日语语音包。'}</p><hr style="border:0;border-top:1px solid var(--line);margin:25px 0"><details><summary>课程与内容说明</summary><p class="sub">覆盖初级上下册 48 课、中级上下册 32 课的课程框架。每课当前包含 2 个原创例句及 6 组核心练习，属于可使用的基础版本，不是完整教材替代品。初级按课次语法主线，中级按话题配置延伸句型，未逐条核对教材全部语法。听力 2 题、阅读与组句 3 题、口语 1 题；口语采用自评，不自动判断发音。</p><p class="sub" style="margin-top:15px">课程结构参考：<a href="https://www.jpedo.com/news/2079.html" target="_blank" rel="noreferrer">新版标日课程目录</a> · <a href="https://www.mitsumura-tosho.co.jp/shoseki/nihongo/s" target="_blank" rel="noreferrer">出版社介绍</a></p></details></div>`}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;render();window.scrollTo(0,0)});document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>{book=Number(b.dataset.book);state.book=book;save();render()});bindStarts();document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say));if($('#goal'))$('#goal').onchange=e=>{state.goal=Number(e.target.value);save();toast('学习目标已保存')};if($('#rate'))$('#rate').onchange=e=>{state.rate=Number(e.target.value);save();toast('朗读语速已保存')};if($('#grammarSearch'))$('#grammarSearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#grammarGrid').innerHTML=grammarCards(lessons.filter(l=>`${l.title}${l.grammar}${l.note}`.toLowerCase().includes(q)));bindStarts()};if($('#reviewStart'))$('#reviewStart').onclick=startReview;}
function bindStarts(){document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(Number(b.dataset.start)))}
function start(id){session={lesson:lessons[id],queue:questions(lessons[id]).map((q,index)=>({...q,id,index})),pos:-1,right:0,graded:0,unscored:0,spoken:false,started:Date.now(),seconds:0};showStudy()}
function startReview(){session={lesson:lessons[state.mistakes[0].id],queue:state.mistakes.map(m=>({...questions(lessons[m.id])[m.index],...m})),pos:0,right:0,graded:0,unscored:0,review:true,started:Date.now(),seconds:0};prepare();showStudy()}
function prepare(){session.selected=null;session.tokens=[];session.checked=false;session.feedback=null;const q=session.queue[session.pos];session.pool=shuffled(q.p.tokens.map((t,i)=>({t,i})));session.options=q.options?shuffled(q.options):[];session.recorded=false;session.skipped=false;session.showText=false;}
function cleanup(){cancelNative();recordPending=false;clearTimeout(recordTimer);if(recorder&&recorder.state!=='inactive'){recorder.onstop=null;recorder.stop()}stream?.getTracks().forEach(t=>t.stop());stream=null;recorder=null;if(audioURL){URL.revokeObjectURL(audioURL);audioURL=null}window.speechSynthesis?.cancel()}
function showStudy(){let overlay=$('.overlay');if(!overlay){overlay=document.createElement('div');overlay.className='overlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','日语练习');document.body.append(overlay);$('.shell').inert=true;document.body.style.overflow='hidden'}const s=session;const q=s.queue[s.pos];const l=q?lessons[q.id]:s.lesson;overlay.innerHTML=`<div class="study"><div class="studyheader"><button class="close" id="quit" aria-label="退出练习">×</button><div class="progress"><span style="width:${Math.max(0,s.pos)/s.queue.length*100}%"></span></div><small>${s.pos<0?'课前手记':Math.min(s.pos+1,s.queue.length)+' / '+s.queue.length}</small></div><div class="eyebrow">${books[l.book].name} · 第 ${l.no} 课 · ${s.review?'错题复习':l.title}</div>${s.pos<0?intro(l):s.pos>=s.queue.length?result():exercise(q,l)}</div>`;$('#quit').onclick=quit;if(s.pos<0){$('#begin').onclick=()=>{s.pos=0;prepare();showStudy()};document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say));}else if(s.pos>=s.queue.length){$('#finish').onclick=quit;}else bindExercise(q);overlay.querySelector('h2')?.setAttribute('tabindex','-1');}
function intro(l){return `<h2>先理解，再练习。</h2><span class="bigjp">${l.grammar}</span><p class="intro">${l.note}</p>${l.pairs.map(p=>`<div class="example"><div><div class="jp" lang="ja">${sentence(p)}</div><p>${p.zh}</p></div><button class="sound" data-say="${esc(sentence(p))}" aria-label="朗读例句">${icon('sound')}</button></div>`).join('')}<div class="checkrow"><span class="muted">2 听力 · 3 阅读与组句 · 1 跟读</span><button class="primary" id="begin">开始练习 ${icon('arrow')}</button></div>`}
function exercise(q,l){const s=session;return `<h2>${q.prompt}</h2>${q.type==='read'?`<div class="bigjp" lang="ja">${sentence(q.p)}</div>`:''}${q.type==='listen'?`<div class="listenarea"><button class="sound" id="play" aria-label="播放日语音频">${icon('sound')}</button><button class="pill" id="slow">慢速播放</button></div><button class="textbtn" id="transcript">${s.showText?'已显示原文，本题不计分':'无法听音？显示原文并跳过计分'}</button>${s.showText?`<p class="bigjp">${sentence(q.p)}</p>`:''}`:''}${q.options?`<div class="options">${s.options.map((o,i)=>`<button class="option ${s.selected===o?'selected':''}" data-option="${i}" ${s.checked?'disabled':''}><span class="key">${i+1}</span>${esc(o)}</button>`).join('')}</div>`:''}${q.type==='build'?`<p class="intro">${q.p.zh}</p><div class="answerline">${s.tokens.map(i=>`<button class="token" data-remove="${i}" ${s.checked?'disabled':''}>${q.p.tokens[i]}</button>`).join('')}</div><div class="tokens">${s.pool.map(({t,i})=>`<button class="token" data-token="${i}" ${s.tokens.includes(i)||s.checked?'disabled':''}>${t}</button>`).join('')}</div>`:''}${q.type==='speak'?`<div class="example"><div><div class="jp" lang="ja">${sentence(q.p)}</div><p>${q.p.zh}</p></div><button class="sound" id="play" aria-label="示范朗读">${icon('sound')}</button></div><div class="recorder"><p>听示范 → 录音 → 回放对比<br>注意句末发音、助词和停顿。本题通过自评完成。</p><button class="primary" id="record">${s.recorded?'重新录音':'开始录音'}</button><div id="recordingArea">${audioURL?`<audio controls src="${audioURL}"></audio>`:''}</div><p id="recordStatus" role="status">${s.recorded?'回放自己的录音，再决定是否掌握。':'录音最长 30 秒，仅用于本次回放。'}</p></div><div style="margin-top:20px"><button class="textbtn" id="skipSpeak">暂时不方便开口，跳过口语</button></div>`:''}${s.feedback?`<div class="feedback ${s.feedback.ok?'':'wrong'}" role="status"><strong>${s.feedback.title}</strong><div>${s.feedback.text}</div></div>`:''}<div class="checkrow"><span class="muted">${q.type==='speak'?'口语自评不计入客观正确率':'慢慢想，不限答题时间'}</span><button class="primary" id="check" ${!s.checked&&(q.type==='build'?s.tokens.length!==q.p.tokens.length:q.type==='speak'?!s.recorded:s.selected===null)?'disabled':''}>${s.checked?'继续':q.type==='speak'?'我已回听并完成跟读':'检查答案'} ${icon('arrow')}</button></div>`}
function bindExercise(q){const s=session;document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{s.selected=s.options[Number(b.dataset.option)];showStudy()});document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{s.tokens.push(Number(b.dataset.token));showStudy()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{s.tokens=s.tokens.filter(i=>i!==Number(b.dataset.remove));showStudy()});if($('#play'))$('#play').onclick=()=>speak(sentence(q.p));if($('#slow'))$('#slow').onclick=()=>speak(sentence(q.p),true);if($('#transcript'))$('#transcript').onclick=()=>{s.showText=true;showStudy()};if($('#record'))$('#record').onclick=record;if($('#skipSpeak'))$('#skipSpeak').onclick=()=>{s.skipped=true;advance()};$('#check').onclick=()=>{if(s.checked){advance();return}if(q.type==='speak'){s.spoken=true;advance();return}const correct=q.type==='build'?s.tokens.map(i=>q.p.tokens[i]).join('')===q.p.tokens.join(''):s.selected===q.answer;if(s.showText)s.unscored++;if(!s.showText){s.graded++;if(correct)s.right++;const exists=state.mistakes.some(m=>m.id===q.id&&m.index===q.index);if(correct&&s.review)state.mistakes=state.mistakes.filter(m=>!(m.id===q.id&&m.index===q.index));else if(!correct&&!exists)state.mistakes.push({id:q.id,index:q.index});save()}s.checked=true;s.feedback={ok:correct,title:s.showText?'已看原文，本题不计分':correct?'理解得很好。':'再看一下这个知识点。',text:`${correct?'':`正确答案：${q.type==='build'?sentence(q.p):esc(q.answer)}<br>`}${lessons[q.id].note}`};showStudy()}}
async function record(){if(isNative()){recordOnIPad();return}if(recordPending)return;if(recorder?.state==='recording'){recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('此浏览器无法录音，请在 localhost 或 HTTPS 下使用支持录音的浏览器。');return}recordPending=true;session.recorded=false;$('#check').disabled=true;const current=session;const pos=session.pos;try{cleanup();const acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(session!==current||session.pos!==pos){acquired.getTracks().forEach(t=>t.stop());return}stream=acquired;recorder=new MediaRecorder(stream);const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{clearTimeout(recordTimer);stream?.getTracks().forEach(t=>t.stop());stream=null;if(session!==current||session.pos!==pos)return;audioURL=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));session.recorded=true;showStudy()};recorder.start();$('#record').textContent='结束录音';$('#recordStatus').textContent='正在录音… 再次点击结束，30 秒后自动停止。';recordTimer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},30000)}catch{toast('没有获得麦克风权限。可在浏览器中允许录音，或跳过本次口语。')}finally{recordPending=false}}

function recordOnIPad(){
  if(recordPending)return;
  if(nativeRecording){stopNativeRecording();return;}
  cleanup();
  const current=session,pos=session.pos;
  recordPending=true;session.recorded=false;$('#check').disabled=true;
  $('#recordStatus').textContent='正在请求麦克风…';
  startNativeRecording({
    onStart(){recordPending=false;if(session!==current||session.pos!==pos){cleanup();return;}$('#record').textContent='结束录音';$('#recordStatus').textContent='正在录音… 最长 30 秒，再次点击结束。';},
    onStop(audio){recordPending=false;if(session!==current||session.pos!==pos)return;audioURL=audio;session.recorded=true;showStudy();},
    onError(message){recordPending=false;if(session===current&&session.pos===pos){showStudy();toast(message);}}
  });
}
window.addEventListener('hiyori-message',e=>toast(e.detail));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&isNative()){cleanup();if(session&&session.queue[session.pos]?.type==='speak'){session.recorded=false;showStudy();}}});

function advance(){cleanup();session.pos++;if(session.pos>=session.queue.length){if(!session.saved){if(!session.review)state.done[session.lesson.id]={at:day(),correct:session.right,total:session.graded,speaking:session.spoken};session.saved=true;save()}}else prepare();showStudy()}
function result(){const s=session;return `<div class="results"><h2>练习完成</h2><p class="sub">${s.review?'答对的题目已移出错题本。':'学习记录已保存。'}</p><div class="resultstats"><strong>${s.graded?`${s.right} / ${s.graded}`:'—'}</strong><span>${s.graded?'客观题答对':'本次未作答计分题'}</span></div><p class="sub">${s.review?'':s.spoken?'口语：已录音、自评完成':'口语：本次已跳过'}${s.unscored>0?' · 显示原文的听力题不计分':''}</p><button class="primary" id="finish">返回课程 ${icon('arrow')}</button></div>`}
function quit(){cleanup();session=null;$('.overlay')?.remove();$('.shell').inert=false;document.body.style.overflow='';render()}
// 仅计入页面可见且正在练习的时间，每秒保存，避免退出或刷新丢失。
setInterval(()=>{if(session&&session.pos<session.queue.length&&!document.hidden){state.days[day()]=(state.days[day()]||0)+1;save()}},1000);
render();

if(preview.lesson!==null){start(preview.lesson);if(preview.step!==null){session.pos=preview.step;prepare();showStudy();}}
